name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache Gradle Wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/wrapper/
        key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Generate Gradle Wrapper
      run: ./gradlew wrapper --gradle-version 7.4

    - name: Build with Gradle (with stacktrace)
      run: ./gradlew build --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
