name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Set up Gradle Wrapper
      run: |
        gradle wrapper

    - name: Build with Gradle (with stacktrace)
      run: ./gradlew build --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
